version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres       # Kullanıcı adı
      POSTGRES_PASSWORD: postgres  # Kullanıcı şifresi
      POSTGRES_DB: postgres-db     # Veritabanı ismi
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
